theme: jekyll-theme-cayman

title: blog
description: haoxin's blog.

encoding: utf-8

gems:
  - jekyll-seo-tag

page_meta:
  description: haoxin's blog.

author:
  name: haoxin
  github: haoxins
  email: haoxinst@gmail.com

highlighter: rouge

markdown: kramdown

defaults:
  scope:
    path: articles
    type: pages
  values:
    sectionid: articles
