theme: jekyll-theme-cayman

title: Hao Xin's Blog
description: Hao Xin's Blog.

encoding: utf-8

page_meta:
  description: Hao Xin's Blog.

author:
  name: Hao Xin
  github: haoxins
  email: haoxinst@gmail.com

highlighter: rouge

markdown: kramdown

defaults:
  -
    scope:
      path: articles
      type: pages
    values:
      sectionid: articles
  -
    scope:
      path: archived
      type: pages
    values:
      sectionid: archived
